### ISSUE TITLE
1.0.0

### ISSUE THREAD

**Issue by dcousens** [alex-seville/travis-cov#11]
Any reason not to be 1.0.0?

**Comment by dcousens** [comment]
ping @alex-seville

**Comment by alex-seville** [comment]
Not actively maintained, but feel free to submit a PR ;)

**Comment by dcousens** [comment]
`npm version major && git push && npm publish` would be all you need to do.
If I submit a PR for the version,  it'll probably more of a hassle than not.

**Comment by dcousens** [comment]
Up to you @alex-seville
