### ISSUE TITLE
Storing configuration in the `scripts` field is no longer supported by npm

### ISSUE THREAD

**Issue by ghost** [alex-seville/travis-cov#2]
`npm` now requires that all `scripts` members be strings (isaacs/npm#4156), so it is no longer possible to store options in the `travis-cov` field like so.

``` js
{
    "scripts": {
        "test-cov": "mocha --require blanket -R travis-cov test/test-*.js",
        "travis-cov": {
            "threshold": 95
        }
    }
}
```

 I can submit a pull request that moves the `travis-cov` configuration elsewhere—and checks `scripts` for backward-compatibility—but wanted to check beforehand. Where should this new field reside?

**Comment by pghalliday** [comment]
+1
