### ISSUE TITLE
Please add License

### ISSUE THREAD

**Issue by harinair** [alex-seville/travis-cov#4]
We are considering using this product for a Pearson project. It is difficult to get legal approval unless you provide a license. It would be much easier for everyone to use if it is MIT license.

https://github.com/blog/1530-choosing-an-open-source-license

**Comment by alex-seville** [comment]
Sure, it will be MIT.  I'll try to add it soon.

It's worth noting that this project isn't being actively maintained, although I do try to respond to issues.

**Comment by alex-seville** [comment]
Added.
