### ISSUE TITLE
Current version on npmjs.org not compatible with latest npm 

### ISSUE THREAD

**Issue by pghalliday** [alex-seville/travis-cov#5]
Now that the config has been moved to the config section in package.json, would it be possible to publish this to npmjs.org. I have started getting issues raised against my own project in which I suggest the use of this module for checking the coverage level.

https://github.com/pghalliday/grunt-mocha-test/issues/43

thanks in advance :)

**Comment by mac-** [comment]
:+1:

**Comment by mako-taco** [comment]
Please publish.  I have published this repo to NPM via `travis-cov-forked` and will take it down when this module has been published, just so people using `grunt-mocha-test` don't get as lost as I did generating coverage reports.

**Comment by bartont** [comment]
+1 Please publish

**Comment by Sauravvaidya** [comment]
Please have this published. :+1:

**Comment by clebert** [comment]
:+1:

**Comment by alex-seville** [comment]
Published 0.2.5 to npm, sorry for the delay.

**Comment by pghalliday** [comment]
Thanks :)
