### ISSUE TITLE
Documentation of options

### ISSUE THREAD

**Issue by thom4parisot** [alex-seville/travis-cov#7]
Hello,

I dug in the code but I struggle to understand what the options stand for:
- removeKey
- global
- local

Sadly, Blanket's `package.json` is no more helpful to understand their meaning nor intent.

Is there anywhere to look at to better understand how to use these settings?

Thanks :-)

**Comment by JamesMGreene** [comment]
+1

**Comment by JamesMGreene** [comment]
As for `global` and `local`: they are no longer valid options, they just weren't 100% cleaned up. I finished the process in my PR #8.
